### ISSUE TITLE
Starts and then crashes before the Main Screen

### ISSUE THREAD

**Issue by pichuwickham** [DrasticDemise/Hubris#12]
I have no idea. It was working fine and I was able to play it. I've tried re-downloading and that doesn't fix it.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 8/5/15 5:25 PM
Description: Initializing game

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1
    at com.google.gson.Gson.fromJson(Gson.java:815)
    at com.google.gson.Gson.fromJson(Gson.java:741)
    at iguanaman.thaumcraftmobaspects.ThaumcraftMobAspects.readFromFile(ThaumcraftMobAspects.java:142)
    at iguanaman.thaumcraftmobaspects.ThaumcraftMobAspects.post(ThaumcraftMobAspects.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1
    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:338)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
    at com.google.gson.Gson.fromJson(Gson.java:803)
    ... 39 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.google.gson.Gson.fromJson(Gson.java:815)
    at com.google.gson.Gson.fromJson(Gson.java:741)
    at iguanaman.thaumcraftmobaspects.ThaumcraftMobAspects.readFromFile(ThaumcraftMobAspects.java:142)
    at iguanaman.thaumcraftmobaspects.ThaumcraftMobAspects.post(ThaumcraftMobAspects.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 539375728 bytes (514 MB) / 2918711296 bytes (2783 MB) up to 6681526272 bytes (6372 MB)
    JVM Flags: 3 total; -Xms256M -Xmx7168M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 102 mods loaded, 101 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UCHIJ   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UCHIJ   AM2-Preloader{0.0.2} [AMCore](minecraft.jar) 
    UCHIJ   Aroma1997Core{1.0.2.13} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.13.jar) 
    UCHIJ   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJ   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJ   WitchingGadgetsCore{1.1.9} [Witching Gadgets Core](minecraft.jar) 
    UCHIJ   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJ   ExtendedPotions{1.1} [Extended Potions](ExtendedPotions-MC1.7.10-1.1.jar) 
    UCHIJ   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJ   arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008.jar) 
    UCHIJ   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJ   FloatingRuins{1.7.10.r02} [FloatingRuins]([1.7.10]FloatingRuins-universal-1.7.10.r02.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8b.jar) 
    UCHIJ   AgriCraft{1.7.10-1.3.1} [AgriCraft](AgriCraft-1.7.10-1.3.1.jar) 
    UCHIJ   AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UCHIJ   Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.13.jar) 
    UCHIJ   AromaBackup{0.0.0.5} [AromaBackup](AromaBackup-1.7.10-0.0.0.5.jar) 
    UCHIJ   Artifacts{1.1.3} [Artifacts](Artifacts-1.1.3.jar) 
    UCHIJ   ATG{0.10.0} [Alternate Terrain Generation](ATG-1.7.10-0.12.0.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJ   Automagy{0.26.2} [Automagy](Automagy-1.7.10-0.26.2.jar) 
    UCHIJ   BattleTowers{1.5.2} [Battle Towers](BattleTowers-1.7.10.jar) 
    UCHIJ   BiblioCraft{1.10.5} [BiblioCraft](BiblioCraft[v1.10.5][MC1.7.10] %281%29.jar) 
    UCHIJ   BiomeTweaker{1.1.120} [BiomeTweaker](BiomeTweaker-1.7.10-1.1.120.jar) 
    UCHIJ   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-11.jar) 
    UCHIJ   Botania{r1.7-207} [Botania](Botania r1.7-207 %281%29.jar) 
    UCHIJ   CarpentersBlocks{3.3.6} [Carpenter's Blocks](Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
    UCHIJ   ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
    UCHIJ   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJ   chisel{2.4.1.40} [Chisel 2](Chisel2-2.4.1.40 %282%29.jar) 
    UCHIJ   ctmlib{1.0.1.5} [CTMLib](Chisel2-2.4.1.40 %282%29.jar) 
    UCHIJ   climatecontrol{0.4} [Climate Control](ClimateControl-0.4.beta17.jar) 
    UCHIJ   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303 %281%29.jar) 
    UCHIJ   CustomChestLoot{1.1.1} [Custom Chest Loot](CustomChestLoot-1.7.10-1.1.1.jar) 
    UCHIJ   CustomMainMenu{1.4} [Custom Main Menu](CustomMainMenu-MC1.7.10-1.4.jar) 
    UCHIJ   defaultworldgenerator{0.1-b13} [Default World Generator](DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) 
    UCHIJ   dldungeonsjdg{1.8.5} [Doomlike Dungeons](DoomlikeDungeons-1.8.5-MC1.7.10 %281%29.jar) 
    UCHIJ   EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UCHIJ   ExtrabiomesXL{3.16.0} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.0.jar) 
    UCHIJ   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJ   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJ   ForbiddenMagic{1.7.10-0.57} [Forbidden Magic](Forbidden Magic-1.7.10-0.57 %281%29.jar) 
    UCHIJ   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   GraveStone{2.12.3} [GraveStone](GraveStone-2.12.4 %281%29.jar) 
    UCHIJ   guideapi{1.7.10-1.0.1-20} [Guide-API](Guide-API-1.7.10-1.0.1-20.jar) 
    UCHIJ   HardcoreEnderExpansion{1.8.2} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.2.jar) 
    UCHIJ   HardcoreQuesting{The Journey (4.2.4)} [Hardcore Questing Mode](HQM-The Journey %284.2.4%29.jar) 
    UCHIJ   InfernalMobs{1.6.0} [Infernal Mobs](InfernalMobs-1.7.10.jar) 
    UCHIJ   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJ   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJ   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJ   journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited %281%29.jar) 
    UCHIJ   launchgui{1.7.10-2.0-17} [LaunchGUI](LaunchGui-1.7.10-2.0-17-client.jar) 
    UCHIJ   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJ   MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
    UCHIJ   MTRM{1.0} [MineTweakerRecipeMaker](MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
    UCHIJ   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.6.jar) 
    UCHIJ   MobProperties{0.3.5} [Mob Properties](MobProperties-1.7.10-0.3.5 %281%29.jar) 
    UCHIJ   NEIAddons{1.12.11.36} [NEI Addons](neiaddons-1.12.11.36-mc1.7.10 %281%29.jar) 
    UCHIJ   NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools](neiaddons-1.12.11.36-mc1.7.10 %281%29.jar) 
    UCHIJ   NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2](neiaddons-1.12.11.36-mc1.7.10 %281%29.jar) 
    UCHIJ   NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany](neiaddons-1.12.11.36-mc1.7.10 %281%29.jar) 
    UCHIJ   NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry](neiaddons-1.12.11.36-mc1.7.10 %281%29.jar) 
    UCHIJ   NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables](neiaddons-1.12.11.36-mc1.7.10 %281%29.jar) 
    UCHIJ   NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo](neiaddons-1.12.11.36-mc1.7.10 %281%29.jar) 
    UCHIJ   neiintegration{1.0.11} [NEI Integration](NEIIntegration-MC1.7.10-1.0.11 %281%29.jar) 
    UCHIJ   NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar) 
    UCHIJ   NodalMechanics{1.7.10R1.0} [NodalMechanics](NodalMechanics-1.7-1.0-7.jar) 
    UCHIJ   harvestcraft{1.7.10i} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10i.jar) 
    UCHIJ   RadixCore{2.0.1} [RadixCore](RadixCore-2.0.1-1.7.10-universal.jar) 
    UCHIJ   RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHIJ   recallstones{0.5.2} [Recall Stones](RecallStones-1.7.10-0.5.2.jar) 
    UCHIJ   RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) 
    UCHIJ   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
    UCHIJ   xreliquary{1.2} [Reliquary](Reliquary-1.2.jar) 
    UCHIJ   ResourceLoader{1.0} [Resource Loader](ResourceLoader-1.0.jar) 
    UCHIJ   Roguelike{1.3.6.3} [Roguelike Dungeons](roguelike-1.7.10-1.3.6.3.jar) 
    UCHIJ   AS_Ruins{14.7} [Ruins Spawning System](Ruins-1.7.10.jar) 
    UCHIJ   runicdungeons{1.1.5c} [Runic Dungeons](runicdungeons-1.1.5c.jar) 
    UCHIJ   SpecialMobs{3.1.1} [Special Mobs](SpecialMobs-1.7.10-3.1.1.jar) 
    UCHIJ   squidless{0.6.1} [Squidless](squidless-1.7.10-0.6.1.jar) 
    UCHIJ   StorageDrawers{1.7.10-1.5.12} [Storage Drawers](StorageDrawers-1.7.10-1.5.12 %281%29.jar) 
    UCHIJ   TaintedMagic{1.1.5.4} [Tainted Magic](TaintedMagic-1.1.5.4.jar) 
    UCHIJ   TConstruct{1.7.10-1.8.6a.build969} [Tinkers' Construct](TConstruct-1.7.10-1.8.6a.jar) 
    UCHIE   ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) 
    UCHIJ   ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-37.jar) 
    UCHIJ   ThaumicHorizons{1.1.5} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.6 %281%29.jar) 
    UCHIJ   thaumicinfusion{4.18} [Thaumic Infusion](ThaumicInfusion-4.18 %281%29.jar) 
    UCHIJ   TravellersGear{1.16.4} [Traveller's Gear](TravellersGear-1.7.10-1.16.4.jar) 
    UCHIJ   WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJ   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCHIJ   WitchingGadgets{1.1.9} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.9.jar) 
    UCHIJ   yampst{1.3.5} [YAMPST](Yampst-Hubris-1.3.1.jar) 
    UCHIJ   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   HungerOverhaul{1.7.10-beta.5.jenkins47} [Hunger Overhaul](HungerOverhaul-1.7.10-beta.5.jar) 
    UD  BiomeTweakerCore{1.1.120} [BiomeTweaker Core](minecraft.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1002' Renderer: 'AMD Radeon R9 200 Series'
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: Environment healthy.
    NetherOres: -[1.7.10]2.3.0-12
    TConstruct Environment: Environment healthy.
    Hardcore Ender Expansion: CAUTION! Ars Magica 2 is not supported by HEE, if the crash is caused by a conflict of the two mods, it will very likely not be possible to fix.
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon R9 200 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1002, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by yarma92** [comment]
@pichuwickham  have you recently updated java? The error is occurring in java during initialization with wrong bits of java attempting to be called. This is usually caused by an incompatible java version. Java 8 u51 is being listed in the report. I launched the pack earlier on windows 10 with a java 7 version and have no issues. If you are using the curse client it uses a Java 8 hotspot to run. You could always try to point the pack at your installed java in the MC launcher when you start the pack and see if it runs that way.

**Comment by pichuwickham** [comment]
@yarma92 I switched to java 7 64 bit and it did not fix this.

**Comment by yarma92** [comment]
Is the crash report identical? If not could you post it?

**Comment by pichuwickham** [comment]
Yes it is the same.

**Comment by DrasticDemise** [comment]
You were playing just fine and then it randomly decides to crash? Do any other packs give you this issue?

**Comment by pichuwickham** [comment]
I was playing fine until I upgraded to Windows 10. At the time I thought it was minecraft's faunt, however now I believe that the drivers for my AMD graphics card are causing things to crash. In fact after the upgrade I can play no game without the entire computer freezing after 5 minutes cause me to hard reset it. I do not believe Minecraft is the issue, I think the issue is the graphics driver. So my only option now is to wait for AMD to fix their windows 10 driver, until then, I can play nothing. :(

**Comment by DrasticDemise** [comment]
Oh. Sorry to hear! I refuse to upgrade until everything is compatible.
