### ISSUE TITLE
1.5.0 - Climate Control b22 server incompatible

### ISSUE THREAD

**Issue by Slind14** [DrasticDemise/Hubris#7]
Hey,

the climate control version b22 is incompatible with servers. I reported the bug to the author and will probably been taken care of soon. Just so you know, it is easy to reproduce with a plain forge server and only the mod climate control.

```
java.lang.NullPointerException: Ticking screen
        at climateControl.ClimateControl.onWorldLoad(ClimateControl.java:124)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_580_ClimateControl_onWorldLoad_Load.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:61)
        at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:238)
        at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
        at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by DrasticDemise** [comment]
Yep I am aware. I will see if downgrading doesn't break anything.

**Comment by DrasticDemise** [comment]
Back ported and fixed.
